categories:
  - name: Urbanization
    short: URB
    color: green
  - name: Work-life balance
    short: WLB
    color: blue
journals:
  - name: Proceedings of the National Academy of Sciences
    short: PNAS
  - name:  Scientific Reports
    short: Sci Rep
  - name: Nature Ecology & Evolution
    short: Nat Ecol Evol
  - name: PLoS Computation Biology
    short: PLoS Comp Bio
conferences:
  - name: Annual Meeting of the Association for Computational Linguistics
    short: ACL
  - name: Empirical Methods in Natural Language Processing
    short: EMNLP
  - name: Computational Natural Language Learning
    short: CoNLL
  - name: Asia-Pacific Chapter of the Association for Computational Linguistics
    short: AACL
  - name: European Chapter of the Association for Computational Linguistics
    short: EACL
  - name: North American Chapter of the Association for Computational Linguistics
    short: NAACL
  - name: Conference on Machine Translation
    short: WMT
  - name: International Conference on Computational Linguistics
    short: COLING
  - name: Language Resources and Evaluation
    short: LREC
  - name: Computer Vision and Pattern Recognition
    short: CVPR
  - name: Neural Information Processing Systems
    short: NeurIPS
  - name: AAAI
    short: AAAI
  - name: International Conference on Machine Learning
    short: ICML
  - name: International Conference on Learning Representations
    short: ICLR
  - name: Building Educational Applications
    short: BEA
  - name: Natural Language Generation, Evaluation and Metrics
    short: GEM
  - name: Representation Learning for NLP
    short: Rep4NLP
  - name: BlackboxNLP
    short: BlackboxNLP
  - name: Fact Extraction and VERification
    short: FEVER
  - name: Neural Generation and Translation
    short: NGT
  - name: Cognitive Modeling and Computational Linguistics
    short: CMCL
  - name: Findings of the Association for Computational Linguistics
    short: Findings
  - name: Nordic Conference on Computational Linguistics
    short: NoDaLiDa
