# Update of Notion DB

name: Update the Notion DB end-to-end manually or on push

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Prepare Selenium
      # https://github.com/marketplace/actions/setup-chromedriver
      uses: nanasess/setup-chromedriver@v1.0.5
    - name: Start XVFB
      run: |
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional, disables headless mode
    - name: Run update script
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        GOOGLE_MAIL: ${{ secrets.GOOGLE_MAIL }}
        GOOGLE_PWD: ${{ secrets.GOOGLE_PASSWORD }}
        NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        PAPERPILE_FOLDER_ID: ${{ secrets.PAPERPILE_FOLDER_ID }}
        COOKIES_PWD: ${{ secrets.COOKIES_PWD }}
        DISPLAY: :99
      run: |
        ./cli update "$PAPERPILE_FOLDER_ID" "$NOTION_DB_ID"
        
        
